version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.20.0
    container_name: blackbox_exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115

  sample_exporter_go:
    build: ./
    container_name: sample_exporter_go
    ports:
      - 19115:19115
